"""Fail on comments that have grown into essays. Limits: CLAUDE.md, "Comments".

Checks every tracked source file. Run with --self-test to check the parsers first.
"""
from __future__ import annotations

import ast
import io
import os
import re
import subprocess
import sys
import tokenize

MAX_RUN = 3            # consecutive whole-line comments: a banner + 2
MAX_HEADER = 5         # the first comment in a file, before any code
MAX_DOCSTRING = 4      # function / class docstring, or a block comment's text
MAX_MODULE_DOC = 5
MAX_JSX = 1            # {/* ... */} inside markup

HASH = (".ps1", ".sh", ".yml", ".yaml", ".toml", ".gitignore", ".gitleaksignore", ".example")
SLASH = (".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".cpp", ".c", ".h", ".hpp")
EXEMPT = re.compile(r"copyright|licen[cs]e|spdx|\.SYNOPSIS", re.I)
# Generated by `supabase init`: its comments are the CLI's commented-out settings template.
GENERATED = {"supabase/config.toml"}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _runs(lines: list[str], is_comment) -> list[tuple[int, int, bool]]:
    """(first line, length, at file start) for each run of consecutive whole-line comments."""
    runs, start, n, code_seen = [], None, 0, False
    for i, line in enumerate(lines + [""], 1):
        if i <= len(lines) and is_comment(line.strip()):
            if start is None:
                start, n = i, 0
            n += 1
            continue
        if start is not None:
            runs.append((start, n, not code_seen))
            start = None
        if line.strip() and i <= len(lines):
            code_seen = True
    return runs


def _check_runs(lines, is_comment, out, source=None):
    source = source or lines
    for start, n, header in _runs(lines, is_comment):
        text = "\n".join(source[start - 1:start - 1 + n])
        limit = MAX_HEADER if header else MAX_RUN
        if n > limit and not EXEMPT.search(text):
            out.append((start, f"{n}-line comment (max {limit})"))


_DELIMS = re.compile(r"^\s*(\{/\*+|/\*+|\*+/?|<!--|<#)?|(\*+/\}?|-->|#>)?\s*$")


def _check_blocks(lines, out, openers: tuple[str, ...], close: str, jsx=False):
    """Block comments, counted by their text lines (delimiter-only lines excluded)."""
    code_seen, i = False, 0
    while i < len(lines):
        s = lines[i].strip()
        opener = next((o for o in openers if s.startswith(o)), None)
        if opener is None:
            code_seen = code_seen or bool(s)
            i += 1
            continue
        j = i
        if close not in s[len(opener):]:
            while j + 1 < len(lines) and close not in lines[j + 1]:
                j += 1
            j = min(j + 1, len(lines) - 1)
        body = lines[i:j + 1]
        if not EXEMPT.search("\n".join(body)):
            if opener == "{/*":
                if jsx and len(body) > MAX_JSX:
                    out.append((i + 1, f"{len(body)}-line JSX comment (max {MAX_JSX})"))
            else:
                n = sum(1 for b in body if _DELIMS.sub("", b).strip())
                limit = MAX_DOCSTRING if code_seen else MAX_HEADER
                if n > limit:
                    out.append((i + 1, f"{n}-line block comment (max {limit})"))
        i = j + 1


def check_python(src: str) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    lines = src.lstrip("﻿").split("\n")
    comment_lines = set()
    try:
        for tok in tokenize.generate_tokens(io.StringIO(src.lstrip("﻿")).readline):
            if tok.type == tokenize.COMMENT and tok.line.strip().startswith("#"):
                comment_lines.add(tok.start[0])
    except (tokenize.TokenError, SyntaxError):
        return [(1, "could not tokenize")]
    marked = [("#" if i in comment_lines and not (i == 1 and l.startswith("#!")) else l)
              for i, l in enumerate(lines, 1)]
    _check_runs(marked, lambda s: s == "#", out, lines)
    try:
        tree = ast.parse(src.lstrip("﻿"))
    except SyntaxError:
        return out + [(1, "could not parse")]
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            doc = ast.get_docstring(node, clean=True)
            if not doc or EXEMPT.search(doc):
                continue
            n = len([l for l in doc.split("\n") if l.strip()])
            limit = MAX_MODULE_DOC if isinstance(node, ast.Module) else MAX_DOCSTRING
            if n > limit:
                line = node.body[0].lineno if node.body else 1
                out.append((line, f"{n}-line docstring (max {limit})"))
    return out


def check_text(path: str, src: str) -> list[tuple[int, str]]:
    src = src.lstrip("﻿")
    lines = src.split("\n")
    out: list[tuple[int, str]] = []
    name = os.path.basename(path).lower()
    if name.endswith(".py"):
        return check_python(src)
    if name.endswith(SLASH):
        _check_runs(lines, lambda s: s.startswith("//"), out)
        _check_blocks(lines, out, ("{/*", "/*"), "*/", jsx=name.endswith((".jsx", ".tsx")))
    elif name.endswith(".sql"):
        _check_runs(lines, lambda s: s.startswith("--"), out)
        _check_blocks(lines, out, ("/*",), "*/")
    elif name.endswith(".css"):
        _check_blocks(lines, out, ("/*",), "*/")
    elif name.endswith(".html"):
        _check_blocks(lines, out, ("<!--",), "-->")
    elif name.endswith(HASH) or name in (".gitignore", ".gitleaksignore"):
        body = [("" if i == 0 and l.startswith("#!") else l) for i, l in enumerate(lines)]
        if name.endswith(".ps1"):
            _check_blocks(body, out, ("<#",), "#>")
            body = _blank_ps1_blocks(body)
        _check_runs(body, lambda s: s.startswith("#"), out)
    return out


def _blank_ps1_blocks(lines):
    out, inside = [], False
    for l in lines:
        s = l.strip()
        if not inside and s.startswith("<#"):
            inside = "#>" not in s[2:]
            out.append("x")
            continue
        if inside:
            inside = "#>" not in s
            out.append("x")
            continue
        out.append(l)
    return out


def tracked_files() -> list[str]:
    r = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True)
    return [f for f in r.stdout.split("\n") if f]


def main() -> int:
    failures = []
    for path in tracked_files():
        if path in GENERATED:
            continue
        try:
            src = open(os.path.join(ROOT, path), encoding="utf-8").read()
        except (OSError, UnicodeDecodeError):
            continue
        for line, msg in check_text(path, src):
            failures.append(f"{path}:{line}: {msg}")
    if failures:
        print("\n".join(failures))
        print(f"\n{len(failures)} comment(s) over the limit. Say only what the code can't; "
              "see CLAUDE.md, \"Comments\".", file=sys.stderr)
        return 1
    print("ok: no comment over the limit")
    return 0


CASES = [
    ("py: three comment lines", "a.py", "# one\n# two\n# three\nx = 1\n", True),
    ("py: four comment lines", "a.py", "x = 0\n# one\n# two\n# three\n# four\nx = 1\n", False),
    ("py: header of five", "a.py", "# 1\n# 2\n# 3\n# 4\n# 5\nx = 1\n", True),
    ("py: header of six", "a.py", "# 1\n# 2\n# 3\n# 4\n# 5\n# 6\nx = 1\n", False),
    ("py: hash inside a string", "a.py", 'x = 0\ns = """\n# a\n# b\n# c\n# d\n"""\n', True),
    ("py: four-line docstring", "a.py", 'def f():\n    """a\n    b\n    c\n    d"""\n', True),
    ("py: five-line docstring", "a.py", 'def f():\n    """a\n    b\n    c\n    d\n    e"""\n', False),
    ("py: six-line module docstring", "a.py", '"""a\nb\nc\nd\ne\nf"""\nx = 1\n', False),
    ("py: licence header", "a.py", "# Copyright x\n# 2\n# 3\n# 4\n# 5\n# 6\n# 7\nx = 1\n", True),
    ("js: four // lines", "a.js", "const a = 1\n// 1\n// 2\n// 3\n// 4\nconst b = 2\n", False),
    ("js: jsdoc of four", "a.js", "const a = 1\n/**\n * 1\n * 2\n * 3\n * 4\n */\nfunction f() {}\n", True),
    ("js: jsdoc of five", "a.js", "const a = 1\n/**\n * 1\n * 2\n * 3\n * 4\n * 5\n */\nfunction f() {}\n", False),
    ("jsx: one-line markup comment", "a.jsx", "const a = (\n  <div>\n    {/* label */}\n  </div>\n)\n", True),
    ("jsx: two-line markup comment", "a.jsx", "const a = (\n  <div>\n    {/* one\n    two */}\n  </div>\n)\n", False),
    ("sql: four -- lines", "a.sql", "select 1;\n-- 1\n-- 2\n-- 3\n-- 4\nselect 2;\n", False),
    ("sql: header of five", "a.sql", "-- 1\n-- 2\n-- 3\n-- 4\n-- 5\nselect 1;\n", True),
    ("ps1: synopsis help is exempt", "a.ps1", "<#\n.SYNOPSIS\n a\n b\n c\n d\n e\n#>\n$x = 1\n", True),
    ("ps1: four # lines", "a.ps1", "$x = 1\n# 1\n# 2\n# 3\n# 4\n$y = 2\n", False),
    ("sh: shebang is not a comment", "a.sh", "#!/bin/bash\n# 1\n# 2\n# 3\n# 4\n# 5\nx=1\n", True),
    ("yml: four # lines", "a.yml", "a: 1\n# 1\n# 2\n# 3\n# 4\nb: 2\n", False),
    ("cpp: four // lines", "a.cpp", "int a;\n// 1\n// 2\n// 3\n// 4\nint b;\n", False),
    ("css: five-line block", "a.css", "a {}\n/*\n 1\n 2\n 3\n 4\n 5\n*/\nb {}\n", False),
]


def self_test() -> int:
    failed = []
    for name, path, src, should_pass in CASES:
        passed = not check_text(path, src)
        if passed != should_pass:
            failed.append(f"  {name}: expected {'pass' if should_pass else 'fail'}, "
                          f"got {'pass' if passed else 'fail'}")
    if failed:
        print("self-test failures:\n" + "\n".join(failed), file=sys.stderr)
        return 1
    print(f"ok: {len(CASES)} self-test case(s) passed")
    return 0


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        raise SystemExit(self_test())
    raise SystemExit(main())
